### ISSUE TITLE
Update pricing plan informations dynamically

### ISSUE THREAD

**Issue by simoneBrancati** [CTMobi/Wubtitle-Wordpress-Plugin#155]
### Feature description

Subscription plan informations should be received from the backend instead of being hardcoded.  
The subscription plan data should be received when one of this events happen:

*  when the plugin is activated
*  when the settings page is updated
*  when the cron updates the job counters

### How the feature is useful

This enforces coherence between the backend database and the frontend application, avoiding to change the plan ids or names if there are changes in the backend or the stripe payment system.

**Comment by simoneBrancati** [comment]
## Responses

### Plugin activation

At plugin activation the response to the Backend API call will be:

```json
{
  "data":{
    "licenseKey":"string",
    "isFree":"boolean",
    "plans":[
      {
        "name":"string",
        "id":"string",
        "rank":"integer",
        "totalJobs":"integer",
        "totalSeconds":"integer",
        "price":"float",
        "text":[ "string", "string" ],
        "icon":"string"
      }
    ]
  }
}
```

### Settings page & Cron

In the settings page call and in the cron call the response will be:

```json
{
  "data":{
    "expirationDate":"integer",
    "isFirstMonth":"boolean",
    "isCanceling":"boolean",
    "currentPlan":"string",
    "consumedJobs":"integer",
    "consumedSeconds":"integer",
    "plans":[
      {
        "name":"string",
        "id":"string",
        "rank":"integer",
        "totalJobs":"integer",
        "totalSeconds":"integer",
        "price":"float",
        "text":[ "string", "string" ],
        "icon":"string"
      }
    ]
  }
}
```

**Comment by cpalessio96** [comment]
To the call to `subscription/info` I added to the body:
`data{
    "sitelang": "string"
}`
the texts are as follows:

for free:
- English 
    - Mp4 Video format allowed
    - Recognized languages: English and Italian
- Italian
    - Formato video consentito: mp4
    - Linguaggi supportati Inglese e Italiano

for professional: 
- English 
    - All wordpress formats supported by wordpress
    - Recognized languages: English, Italian, German, French, Spanish and Chinese
- Italian
    - Tutti i formati supportati da wordpress
    - Lingue supportate: Inglese, Italiano, Tedesco, Francese, Spagnolo, Cinese

for elite:
- English 
    - All wordpress formats supported by wordpress
    - Recognized languuages: English, Italian, German, French, Spanish and Chinese
- Italian
    - Tutti i formati supportati da wordpress
    - Lingue supportate: Inglese, Italiano, Tedesco, Francese, Spagnolo, Cinese
