### ISSUE TITLE
Create a stripe custom form

### ISSUE THREAD

**Issue by cpalessio96** [CTMobi/Wubtitle-Wordpress-Plugin#165]
## Feature request
Replace the stripe form with a custom form.

### Feature description
- Create a custom form to add new fields related to invoice information.
    - use the stripe elements api and create the form using react
- Create a endpoint to receive PaymentIntention data from backend.
- Send the payment information and the invoice information to stripe.
### How the feature is useful
- Allows the user to enter data to receive an invoice

**Comment by simoneBrancati** [comment]
## PAYMENT DETAILS

This part of the form collects data about the subscription payment. The form fields are:

*  **Name**:  [REQUIRED]
*  **Lastname**:  [REQUIRED]
*  **Email**:  [REQUIRED]
*  **Card number**  [REQUIRED], validated by Stripe
*  **CVC**  [REQUIRED], validated by Stripe
*  **Postal Code**  [REQUIRED], validated by Stripe

## BILLING DETAILS

This describes the details needed for the *electronic invoice*.  
The form fields are:

*  **Name**:  [REQUIRED]
*  **Lastname**:  [REQUIRED]
*  **Email**: [REQUIRED]
*  **Telephone**: [REQUIRED]
*  **Company Name**:  [OPTIONAL]
*  **Address**:  [REQUIRED]
*  **Postal Code**:  [REQUIRED]
*  **City**:  [REQUIRED]
*  **Province**:  [REQUIRED]
*  **Country**:  [REQUIRED]
*  **VatCode** [OPTIONAL*]
*  **Fiscal Code**:  [OPTIONAL*]


\*  If **Company Name** is filled, then VatCode is REQUIRED, if is empty **Fiscal code** is REQUIRED.

**Comment by cpalessio96** [comment]
@danielapetix the fields are those above, the **name**, **lastname** and **email** fields are duplicated, one for payment and one for the invoice. 
If the user selects Italy as a **country**, he must also fill in the **province**, **destinationcode** and **postalcode**.
Also, if the user is a company,he must enter the company name of course and the **VAT CODE** (P.iva).

**Comment by simoneBrancati** [comment]
## VAT collectability

| **State/Region**                | **Private customer** | **Business customer**                                                  |
|:-------------------------------:|:--------------------:|:----------------------------------------------------------------------:|
| Italy                           | IVA 22%              | IVA 22%                                                                |
| European Union \(except Italy\) | IVA 22%              | <ul><li>VIES registered business: IVA 0 %</li><li>No Vies registration: IVA 22 %</li></ul> |
| Outside European Union          | IVA 22%              | IVA 0%                                                                 |

**Comment by danielapetix** [comment]
@cpalessio96 Here you can see subscription mockup and flow: 
https://xd.adobe.com/view/47627c7e-64f8-4a52-9522-f983ddc89ca7-1231/
Here you can also see all the cases for foreign, EU and Italian users and for companies and individuals

**Comment by danielapetix** [comment]
@nicola-palermo @cpalessio96 here is the mobile version mockup of Payment and Billing details editing: https://xd.adobe.com/view/2ebf7752-9ce8-40fa-b06b-4face82d90a4-7bec/
Please, change the copy in plugin setting from "Update email or payment detail" to "Update billing or payment details" for english version and from "Aggiorna email o dettagli pagamento" to "Aggiorna dettagli di fatturazione o pagamento" forn Italian Version
