### ISSUE TITLE
Get invoice data to precompile the update form

### ISSUE THREAD

**Issue by cpalessio96** [CTMobi/Wubtitle-Wordpress-Plugin#190]
## Feature request
In the payment data update form the invoice data form must be pre-filled with the current fields previously entered by the user

### Feature description
To do this you need to call the aws backend which will retrieve the data from stripe/fattura24 for us

### How the feature is useful
The user will not need to remember the fields entered in a previous invoice

@simoneBrancati  write me the endpoint documentation when you are done

the data I need at the moment are all the invoice data : 

- invoice name

- invoice lastname

- invoice email 

- telephone

- country 

- city 

- address

- vat code

- fiscal code

- company name

- postal code

- province

- destination code

**Comment by simoneBrancati** [comment]
The response will have this structure:

```json
{
  "Name":"string",
  "LastName":"string",
  "Email":"string",
  "Telephone":"string",
  "CompanyName":"string",
  "Address":"string",
  "PostCode":"string",
  "City":"string",
  "Province":"string",
  "Country":"string",
  "VatCode":"string",
  "FiscalCode":"string",
  "DestinationCode":"string"
}
```

**Comment by simoneBrancati** [comment]
The request MUST have the license key in the headers as "licenseKey".

**Comment by cpalessio96** [comment]
add **TelephonePrefix** to data

**Comment by cpalessio96** [comment]
@simone we have to add the fields for the payment form, can you update the response structure?

**Comment by cpalessio96** [comment]
in paymentDetails i need the paymentMethodId

**Comment by simoneBrancati** [comment]
> in paymentDetails i need the paymentMethodId

fixed
