### ISSUE TITLE
Billing and payment custom form and flow mockup

### ISSUE THREAD

**Issue by danielapetix** [CTMobi/Wubtitle-Wordpress-Plugin#205]
Realization of the payment and billing flow mockup based on the specs contained in the issue #165 . Generation of related design specs

**Comment by danielapetix** [comment]
@nicola-palermo @cpalessio96 Here is the "Update billing or payment details" mockup.
Desktop version: 

- [Billing page](https://xd.adobe.com/view/2ebf7752-9ce8-40fa-b06b-4face82d90a4-7bec/specs/)

- [Payment page (with editing mode enabled and disabled)](https://xd.adobe.com/view/2ebf7752-9ce8-40fa-b06b-4face82d90a4-7bec/screen/815a80ee-561e-4c07-80be-8973aa39800e/specs/)

Smartphone version:

- [Billing page](https://xd.adobe.com/view/2ebf7752-9ce8-40fa-b06b-4face82d90a4-7bec/screen/0a443482-3468-4f23-934c-12abfc1586b3/specs/)

- [Payment page (with editing mode enabled and disabled)](https://xd.adobe.com/view/2ebf7752-9ce8-40fa-b06b-4face82d90a4-7bec/screen/4a05f2cd-dbee-4028-9a27-8bf9252e0844/specs/)

**Comment by nicola-palermo** [comment]
@danielapetix mockup was applied, it needs review.

**Comment by danielapetix** [comment]
@cpalessio96 @nicola-palermo here is the [review spreadsheet](https://docs.google.com/spreadsheets/d/18elI4eUCSupK0_iwBb1onmlLDjIx4jm7utPqp6kj94U/edit?usp=sharing). Is still in progress
