### ISSUE TITLE
Support 3d secure cards.

### ISSUE THREAD

**Issue by cpalessio96** [CTMobi/Wubtitle-Wordpress-Plugin#239]
## Feature request

Support 3d secure cards.

### Feature description

Use the stripe function confirmcardPayment() for confirm payment after the user has entered the 3d code

**Comment by cpalessio96** [comment]
const response = await @simoneBrancati

**Comment by sim1Bk** [comment]
At the first payment, the backend response will be:

```jsonc
{
  "data": {
      "status": "string" // "requires_action" or "complete",
      "clientSecret" : "string" // only if status = "requires_action"
   }
}
```

**Comment by sim1Bk** [comment]
# COMPLETE CUSTOM CHECKOUT FLOW

### Subscription creation

At first payment the frontend will call the endpoint `/stripe/checkout/setup` with a POST request:

```jsonc
{
  "headers":{
    "licenseKey":"string",
    "domainUrl":"string"
  },
  "body":{
    "data":{
      "email":"string",
      "siteLang":"string",
      "invoiceDetails":"object",
      "action":"string", // always assumes the value of "create" in this case
    }
  }
}
```

The response to this call will be

**201 Created**
```jsonc
{
 "body": {
    "data": {
        "clientSecret" : "string"
     }
  }
 }
```

After confirming the SetupIntent another call must be made to the endpoint `/stripe/checkout/confirm`:

```jsonc
{
  "headers":{
    "licenseKey":"string",
    "domainUrl":"string"
  },
  "body":{
    "data":{
      "planId":"string",
      "setupIntent":"object",
      "action":"string", // always assumes the value of "create" in this case
    }
  }
}
```

The response will be:

**200 OK**
```jsonc
{
    "data": {
      "status": "string" // "requires_action" or "complete",
      "clientSecret" : "string" // only if status = "requires_action"
     }
 }
```

This response will prompt the confirmation of the payment.

### Subscription update

#### 1.Update only invoice details

There will be only one call to the endpoint `/stripe/checkout/setup`:

```jsonc
{
  "headers":{
    "licenseKey":"string",
    "domainUrl":"string"
  },
  "body":{
    "data":{
      "email":"string",
      "siteLang":"string",
      "invoiceDetails":"object",
      "action":"string", // always assumes the value of "updateInvoice" in this case
    }
  }
}
```

The response will be only the status code **201** without body.

#### 2.Update card details and invoice details

Two calls, the first to the endpoint `/stripe/checkout/setup`:

```jsonc
{
  "headers":{
    "licenseKey":"string",
    "domainUrl":"string"
  },
  "body":{
    "data":{
      "email":"string",
      "siteLang":"string",
      "invoiceDetails":"object",
      "action":"string", // always assumes the value of "updateCard" in this case
    }
  }
}
```

The response will be:

**201 Created**
```jsonc
{
    "data": {
        "clientSecret" : "string"
     }
 }
```

This will prompt the SetupIntent confirmation, after which the frontend must call the endpoint `/stripe/checkout/confirm`:

```jsonc
{
  "headers":{
    "licenseKey":"string",
    "domainUrl":"string"
  },
  "body":{
    "data":{
      "setupIntent":"object",
      "action":"string", // always assumes the value of "updateCard" in this case
    }
  }
}
```

The response will be:

**200 OK** without a body

**Comment by sim1Bk** [comment]
### MINOR FIXES

*   The call to the endpoint `/stripe/customer/invoice-details` won't send the `paymentMethodId` inside `data.paymentDetails` in response.

*   The `type` flag in the call to the endpoint `/stripe/customer/update/` is no longer needed
