### ISSUE TITLE
Settings page not updating after plan update

### ISSUE THREAD

**Issue by sim1Bk** [CTMobi/Wubtitle-Wordpress-Plugin#246]
#### Steps to reproduce the issue

1.  Go to the Wubtitle settings page
2.  When in Professional plan click on 'Upgrade'
3.  Choose 'Elite plan' and upgrade you subscription
4.  After the update popup window closes and the 'Payment successful' notice appears the subscription data don't get updated.

#### What I expected

The plan information should have been that about the Elite Plan.

#### What happened instead
The plan information remained Professional until i hit the refresh button

**Screenshots**

**Comment by cpalessio96** [comment]
the issue has been resolved with the thank you page #282
