### ISSUE TITLE
Add field to the form for discount code

### ISSUE THREAD

**Issue by cpalessio96** [CTMobi/Wubtitle-Wordpress-Plugin#255]
## Feature request
Add field for discount code, on insert( or on click button 'apply discount' ) the code will be verified and validated and the discount will be calculated.

The coupon can also be inserted during an upgrade

**Comment by cpalessio96** [comment]
need an update to the mockup @danielapetix

**Comment by sim1Bk** [comment]
## Request

#### Headers

```json
{
   "licenseKey": "string",
   "domainUrl": "string"
}
```

#### Body

```json
{
  "data":{
     "coupon":"string",
     "planId":"string"
  }
}
```

## Response

### Code
200

### Body
```json
{
  "data":{
     "discountedAmount":"string",
  }
}
```
