### ISSUE TITLE
Add support for 3d secure cards to upgrade

### ISSUE THREAD

**Issue by cpalessio96** [CTMobi/Wubtitle-Wordpress-Plugin#258]
## Feature request
Add modal for payment confirm by secure 3d authentication to the upgrade plan

### Feature description
Some cards at the time of the upgrade went wrong because they need authentication at every payment.

@simoneBrancati 
at the 'stripe/customer/update/preview' endpoint i need this new data:
```
body: {
  data: {
    AmountPreview
    name
    email
    expiration
    cardNumber
  }
}

````

and for 'stripe/customer/update' endpoint' i need: 
```
body: {
  data: {
    status:
    paymentMethod 
    clientSecret
  }
}

````

@danielapetix  I need an update to the mockup for the upgrade / downgrade confirmation page.
The page must now contain the following info:
- Name card holder

- Email card holder

- Card Number (last 4 characters)

- Card expiration date

**Comment by danielapetix** [comment]
@cpalessio96, here you can find the updated upgrade page with payment details:  https://xd.adobe.com/view/15e994f3-cef1-44c5-61df-df328664557c-63d8/screen/bb38c9cc-fc03-4a71-9451-cf41a006d80a/
