### ISSUE TITLE
phpcs Warning and error

### ISSUE THREAD

**Issue by GiuseppeIuculano** [CTMobi/Wubtitle-Wordpress-Plugin#340]
We need to fix or silent phpcs Warning and error, and understand why travis doesn't warn anymore

**Comment by cpalessio96** [comment]
I removed paranoia mode and silenced 2 warnings:

- **PHPCS_SecurityAudit.BadFunctions.FilesystemFunctions.WarnFilesystem**  This warns that functions like dirname (__FILE__) use dynamic parameters

- **PHPCS_SecurityAudit.BadFunctions.CallbackFunctions.WarnCallbackFunctions**  this warns that there are functions that support callbacks

 I fixed the errors reported by phpcs and fixed config phpcs, problem a was the exclude of `/build`.

I still managed to delete build with the following notation `^build/`
